# Generated by Django 5.0.2 on 2024-04-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0026_transfer_delete_veterinarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(default='Pending', max_length=200, null=True),
        ),
    ]
